version: "3.8"

services:
  database:
    container_name: comics_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: JHYGD7quwj
      MYSQL_DATABASE: comics
      MYSQL_USER: comics
      MYSQL_PASSWORD: gfhjkm
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
  
  php:
    container_name: comics_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/var/www/comics
    depends_on:
      - comics_database

  nginx:
    container_name: comics_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
      - '8081:81'
    volumes:
      - ./backend:/var/www/comics
      - ./frontend:/var/www/comics-frontend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - comics_php
      - comics_database